### PR TITLE
Added check for Windows to prevent load of pty

### PR DESCRIPTION
**Pull request by Lord-Fisch**
Fix for Issue #819

### CODE REVIEW

**Comment by unixmonkey** [comment]
Took awhile to get setup to actually try this out. Thanks!

**Comment by crutch12** [comment]
@unixmonkey thx. When will you release this? :)

**Comment by unixmonkey** [comment]
Later today or tonight, I think. I'm planning to bundle it with #821 which several people have been waiting for, and release a new patch version to Rubygems.

**Comment by unixmonkey** [comment]
Version `1.2.2` has been released which includes this fix. Thank you for your help!

**Pull request merged**
