### PR TITLE
Positively use ActionController::Base.helpers.asset_path

### PR DESCRIPTION
**Pull request by stefanwild**
For some reason that I couldn't figure out I had to change this to make paths work in my production environment. Not sure if it applies to other setups as well.

### CODE REVIEW

**Comment by unixmonkey** [comment]
Weird. Can you post what versions of Rails and Sprockets?

**Comment by stefanwild** [comment]
Rails 4.2.7.1
Sprockets 3.7.0

**Comment by nigeretsky** [comment]
-# Wicked PDF [Build Status](http://travis-ci.org/mileszs/wicked_pdf) [Gem Version](http://badge.fury.io/rb/wicked_pdf)
 +# Wicked PDF [Build Status](http://travis-ci.org/mileszs/wicked_pdf) [Gem Version](http://badge.fury.io/rb/wicked_pdf) [Code Climate](https://codeclimate.com/github/mileszs/wicked_pdf)

**Comment by unixmonkey** [comment]
Is anyone else affected by this?

I'm closing for now, but if this is still an issue, let me know and I'll reopen and dig in.

**Pull request closed without merging**
