### PR TITLE
Encapsulate binary path and version handling

### PR DESCRIPTION
**Pull request by adzap**
Cleans up main class and allows refactoring of path handling.

Binary path discovery can be complex it seems and this offers a path to improved handling or overriding if necessary. 

Long term goal of combining extracted option parsing and this to allow a command class to combine and execute and return result.

I think these combined PRs provide a path to a well factored and a cleaner handling gem's functions.

### CODE REVIEW

**Comment by adzap** [comment]
Same problem with the build again.

**Comment by unixmonkey** [comment]
Rebuild passed :)

**Comment by adzap** [comment]
thanks! 

The overall ambition, to be able to combine an option parser object with a binary object consumed by a command object which handles the actual cli execution. This is coordinated by a document object that is home to pdf_from_string, pdf_from_url etc. methods.

Decoupled, testable, customisable.

**Comment by adzap** [comment]
This redesign would support things like #768 much more easily and cleanly.

**Comment by unixmonkey** [comment]
I had to resolve some minor merge conflicts related to `xvfb`, but this is now merged.

Thanks!

**Pull request merged**
