### PR TITLE
Update to version 2.0.0

### PR DESCRIPTION
**Pull request by jdongelmans**
Updated version to `2.0.0`, so we can have a release which plays nice with Rails 6 😄

### CODE REVIEW

**Comment by TejuGupta** [comment]
Hi, got to this PR from [here](https://github.com/rails/rails/issues/36546) and learnt that this might fix the ActionText issue we are facing as part of our Rails 6 upgrade. Do you have a tentative date for this release?

**Comment by unixmonkey** [comment]
@jdongelmans After looking this over closely, and integrating into a freshly-generated Rails 6.0.2 app, I think this is good to release. However, because we dropped support for Ruby versions under 2.2, and Rails versions under 4, I think this should be a SEMVER breaking change, and should be version `2.0.0`.

Do you think you could make that change? I'd like you to get some credit for this PR, but don't necessarily want a commit changing to 1.5.0 and that never getting a related release.

**Comment by jdongelmans** [comment]
@unixmonkey you are right, I've changed the version to `2.0.0` and moved the relevant issue to the Breaking changes section in `CHANGELOG.md`

**Comment by unixmonkey** [comment]
Version 2.0 is now released. Thanks for the help and the push to get this out there.

**Pull request merged**
