### PR TITLE
Add frozen_string_literal magic header

### PR DESCRIPTION
**Pull request by n-rodriguez**
Thank you!

### CODE REVIEW

**Comment by n-rodriguez** [comment]
@unixmonkey  rebased! thank you!

**Comment by n-rodriguez** [comment]
ping @unixmonkey

**Comment by n-rodriguez** [comment]
ping @unixmonkey

**Comment by n-rodriguez** [comment]
This PR is avoid to avoid regressions. See: https://gist.github.com/fxn/bf4eed2505c76f4fca03ab48c43adc72

**Review by unixmonkey — APPROVED** [review]

**Pull request merged**
