### PR TITLE
Fix Rails5 deprecation warning

### PR DESCRIPTION
**Pull request by takkanm**
ref: #510 

I tried fix deprecation warning.

### CODE REVIEW

**Comment by codeodor** [comment]
Are you not getting a bunch of these deprecations too?

```
DEPRECATION WARNING: `render :text` is deprecated because it does not actually render a `text/plain` response. Switch to `render plain: 'plain text'` to render as `text/plain`, `render html: '<strong>HTML</strong>'` to render as `text/html`, or `render body: 'raw'` to match the deprecated behavior and render with the default Content-Type, which is `text/plain`. (called from render_with_wicked_pdf at /Users/sam/.rvm/gems/ruby-2.3.0@cte/bundler/gems/wicked_pdf-8f970f29c4de/lib/wicked_pdf/pdf_helper.rb:22)
```

**Comment by codeodor** [comment]
One error I get with this when I add `gem 'wicked_pdf', github: 'takkanm/wicked_pdf', branch: 'fix_warning_in_rails5'` to my `Gemfile` and run my tests is: 

```
ActionView::Template::Error: No such file or directory @ rb_sysopen - ~/myapp/public/stylesheets/application.css
    app/views/layouts/print.html.erb:5:in `_app_views_layouts_print_html_erb__3725552830765960760_70238720917040'
    ...
```

If I switch it to `gem 'wicked_pdf', github: 'mileszs/wicked_pdf'` there is no problem though.

**Comment by unixmonkey** [comment]
Thanks a lot!

**Comment by Carlows** [comment]
hey guys, the gem is still throwing me these deprecation warnings, and I'm using version `1.0.6`, they only happen in my test enviroment though :confused:

**Pull request merged**
